## обновление записи по залогу
POST https://1c_url/update_loan
Content-Type: application/json

{
  "UUID": "b0291e09-dae8-47bb-b380-9c25be22fab3",
  "productUUID": "b0291e09-dae8-47bb-b380-9c25be22fab3",
  "department": "8d7850b3-8bc9-11e7-86a2-1c1b0de4e1bd",
  "productSum": 50000.12,
  "currency": "RUR",
  "annualRate": 28.5,
  "paymentType": "аннуитет",
  "mainDebt": 78000,
  "dateOfIssue": "15/03/2023",
  "endDate": "15/06/2023",
  "dateOfPayment": 28,
  "daysInYear": 365,
  "roundingTo": 2,
  "periodicityOfPayment": "неделя",
  "isFirstTime": true,
  "hasCommissions": true,
  "hasPenalty": true,
  "pledge": [
    {
      "deposit": true,
      "pledge": true,
      "guarantee": true
    }
  ],
}