POST https://1c_url/update_client_finance_data
Content-Type: application/json

{
  "guid": "b0291e09-dae8-47bb-b380-9c25be22fab3",
  "averageMainIncome": 40000,
  "averageExtraIncome": 401,
  "monthlyMandatoryPayment": 23100
}