POST https://1c_url/update_client_contact_data
Content-Type: application/json

# fact - фактический адрес проживания
# register - прописка
{
  "guid": "b0291e09-dae8-47bb-b380-9c25be22fab3",
  "address": {
      "fact": {
        "country": "РОССИЯ",
        "zip": "633011",
        "region": "Новосибирская обл",
        "city": "Бердск",
        "street": "Морская улица",
        "house": "112",
        "body": "1",
        "flat": "56",
      },
      "register": {
        "country": "РОССИЯ",
        "zip": "633011",
        "region": "Новосибирская обл",
        "city": "Бердск",
        "street": "Морская улица",
        "house": "112",
        "body": "1",
        "flat": "56",
      }
  },
  "mobilePhone": "79139290012"
}