## создание записи по Клиенту (физ лицо)
POST https://1c_url/create_client_person
Content-Type: application/json

{
  "lastName": "Кутузов",
  "firstName": "Геннадий",
  "midName": "Игоревич",
  "birthday": "15/01/1967",
  "sex": "М",
  "placeOfBirth": {
    "region": "Красноярский край",
    "city": "Красноярск"
  },
  "inn": "213124234234",
  "nameHistory": [], // тут массив из clientNameHistory
  "clientCardNumber": {}, // тут объект clientCardNumber
  "clientContactData": {}, // тут объект clientContactData
  "clientDocument": {}, // тут объект clientDocument
  "clientFinanceData": {}, // тут объект clientFinanceData
}