POST https://1c_url/update_client
Content-Type: application/json

## если guid не передаем, значит создание новой записи. Если guid указан, то редактирование существующей
{
  "guid": "b0291e09-dae8-47bb-b380-9c25be22fab3",
  "lastName": "Кутузов",
  "firstName": "Геннадий",
  "midName": "Игоревич",
  "birthday": "15/01/1967",
  "sex": "М",
  "placeOfBirth": "Красноярск",
  "inn": "213124234234",
  "nameHistory": [
    {
      "lastName": "Зюганов",
      "firstName": "Палладий",
      "midName": "Сидорович",
      "endDate": "15/02/1997"
    },
    {
      "lastName": "Гадя",
      "firstName": "Акакий",
      "midName": "Ивановович",
      "endDate": "15/02/1986"
    }
  ]
}